Repository ContainerSolutions/Jeeves, pull requests merged in 2020-12, with the labels that each got.

#1 Updated Security
  manifests/base/deployment.yaml
  pkg/router/router.go
  pkg/slack/slack.go
  pkg/slack/slack_test.go
Labels: enhancement

#2 Added Github Actions and Paul
  .github/workflows/main.yaml
  PAUL.yaml
  anonymizer/Readme.md
Labels: automation

#3 Refactored to use Slash Commands
  Dockerfile
  go.mod
  go.sum
  manifests/base/deployment.yaml
  manifests/base/ingress.yaml
  manifests/production/kustomization.yaml
  manifests/staging/ingress.patch.yaml
  manifests/staging/kustomization.yaml
  manifests/staging/rolebinding.patch.yaml
  pkg/commands/commands.go
  pkg/commands/commands_test.go
  pkg/config/config.go
  pkg/kubernetes/jobs.go
  pkg/router/router.go
Labels: enhancement, merge

#4 Added namespace to prod
  manifests/production/kustomization.yaml
Labels: bug, merge

#6 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, merge

#14 Lowercased the git user name and removed the < > special characters
  pkg/commands/commands.go
Labels: bug, merge

#5 Create LICENSE
  LICENSE
Labels: documentation, merge

#15 Feature GitHub config
  README.md
  go.mod
  go.sum
  manifests/base/deployment.yaml
  manifests/base/secrets.enc
  manifests/production/secrets.enc
  manifests/staging/secrets.enc
  pkg/commands/commands.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/kubernetes/jobs.go
  pkg/router/router.go
  scripts/decrypt
  scripts/encrypt
Labels: enhancement, merge

#16 Release workflow
  .github/workflows/main.yaml
Labels: enhancement

#18 Added functionality to allow for both github or gitlab
  anonymizer/scripts/anonymize-repo.sh
  pkg/commands/commands.go
  pkg/commands/commands_test.go
  pkg/kubernetes/jobs.go
Labels: enhancement
